name: test

on:
  push: ~

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'hiddewie/OpenRailwayMap-vector'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PACKAGES_TOKEN }}

      # Runs a set of commands using the runners shell
      - name: pull
        run: |
          docker pull ghcr.io/hiddewie/openrailwaymap-data:latest

  deploy-proxy:
    name: Deploy proxy
    runs-on: ubuntu-latest
    # environment: proxy-production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'hiddewie/OpenRailwayMap-vector'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      # Manually write import bounds, to decouple proxy from tile generation/import
      - name: Output import bounds
        run: |
          jq -c '
            [.[].bboxes] | flatten | [
              [
                (map(split(",")[0] | tonumber) | min),
                (map(split(",")[1] | tonumber) | min)
              ],
              [
                (map(split(",")[2] | tonumber) | max),
                (map(split(",")[3] | tonumber) | max)
              ]
            ]
          ' tiles/deploy-bboxes.json > data/import/bounds.json

      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --config proxy.fly.toml --local-only
